<a href="https://colab.research.google.com/github/MuhamadFahmiii/Desain-Analisis-Algoritma/blob/main/tugas_peretmuan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [8]:
#latihan 1
from datetime import date

# Membuat list Mahasiswa
mahasiswa = [
    {
        "Nama": "Muhamad Fahmi",
        "NIM": "2022071026",
        "Prodi": "Teknik Informatika",
        "Mata Kuliah": "Desain Analisis Algoritma",
        "Tanggal Hari Ini": date.today().strftime("%Y-%h-%d"),
        "Nama Universitas": "UPJ"
    },

]

# Menampilkan list Mahasiswa
for mhs in mahasiswa:
    print("Nama:", mhs["Nama"])
    print("NIM:", mhs["NIM"])
    print("Prodi:", mhs["Prodi"])
    print("Mata Kuliah:", mhs["Mata Kuliah"])
    print("Tanggal Hari Ini:", mhs["Tanggal Hari Ini"])
    print("Nama Universitas:", mhs["Nama Universitas"])
    print("\n")

Nama: Muhamad Fahmi
NIM: 2022071026
Prodi: Teknik Informatika
Mata Kuliah: Desain Analisis Algoritma
Tanggal Hari Ini: 2023-Sep-13
Nama Universitas: UPJ




In [9]:
import datetime
today_date = datetime.datetime.today()
date_list = [today_date.year, today_date.month,today_date.day]

In [10]:
#latihan 2

bin_color=['20392302', '1132321', '1311213131']
bin_color[0]

'20392302'

In [11]:
#NIM
mahasiswa = [
      {
        "Nama": "Muhamad Fahmi",
        "NIM": "2022071026",
        "Prodi": "Teknik Informatika",
        "Mata Kuliah": "Desain Analisis Algoritma",
        "Tanggal Hari Ini": date.today().strftime("%Y-%h-%d"),
        "Nama Universitas": "UPJ"
     },
     {
        "Nama": "John Doe",
        "NIM": "123456789",
        "Prodi": "Teknik Informatika",
        "Mata Kuliah": "Pemrograman Python",
        "Tanggal Hari Ini": date.today().strftime("%Y-%m-%d"),
        "Nama Universitas": "Universitas Contoh"
    },
    {
        "Nama": "Jane Smith",
        "NIM": "987654321",
        "Prodi": "Manajemen",
        "Mata Kuliah": "Manajemen Strategis",
        "Tanggal Hari Ini": date.today().strftime("%Y-%m-%d"),
        "Nama Universitas": "Universitas Contoh"
    }

]
for i in range(len(mahasiswa)):
    print("NIM Mahasiswa ke-", i + 1, ":", mahasiswa[i]["NIM"])

NIM Mahasiswa ke- 1 : 2022071026
NIM Mahasiswa ke- 2 : 123456789
NIM Mahasiswa ke- 3 : 987654321


In [12]:
#nama universitas
mahasiswa = [
      {
        "Nama": "Muhamad Fahmi",
        "NIM": "2022071026",
        "Prodi": "Teknik Informatika",
        "Mata Kuliah": "Desain Analisis Algoritma",
        "Tanggal Hari Ini": date.today().strftime("%Y-%h-%d"),
        "Nama Universitas": "UPJ"
     },
     {
        "Nama": "John Doe",
        "NIM": "123456789",
        "Prodi": "Teknik Informatika",
        "Mata Kuliah": "Pemrograman Python",
        "Tanggal Hari Ini": date.today().strftime("%Y-%m-%d"),
        "Nama Universitas": "Unchdip"
    },
    {
        "Nama": "Jane Smith",
        "NIM": "987654321",
        "Prodi": "Manajemen",
        "Mata Kuliah": "Manajemen Strategis",
        "Tanggal Hari Ini": date.today().strftime("%Y-%m-%d"),
        "Nama Universitas": "unbrow"
    }

]
for i in range(len(mahasiswa)):
    print("NIM Mahasiswa ke-", i + 1, ":", mahasiswa[i]["Nama Universitas"])

NIM Mahasiswa ke- 1 : UPJ
NIM Mahasiswa ke- 2 : Unchdip
NIM Mahasiswa ke- 3 : unbrow


In [13]:
#latihan 3 (slicing)
data_mahasiswa = "12345678", "Teknik Informatika", "UPJ",

In [14]:
nim = data_mahasiswa[0:1]  # Mengambil 8 karakter pertama (NIM)
prodi = data_mahasiswa[1:2]  # Mengambil karakter mulai dari indeks 11 sampai akhir (Prodi)
univ = data_mahasiswa[2:3]

print("NIM:", nim)
print("Prodi:", prodi)
print("UNIV:", univ)


NIM: ('12345678',)
Prodi: ('Teknik Informatika',)
UNIV: ('UPJ',)


In [15]:
#latihan 4

bin_Mahasiswa = ["Najib", "Fahmi", "Daffa", "Ican"]

for aMahasiswa in bin_Mahasiswa:
  print("UPJ " + aMahasiswa )

UPJ Najib
UPJ Fahmi
UPJ Daffa
UPJ Ican


In [16]:
#latihan 5
UPJ = ("Universitas", "Pembangunan", "Jaya")



In [17]:
elemen_pertama = UPJ[2]
print(elemen_pertama)  # Output: Universitas


Jaya


In [18]:
hariawal = ("senin", "selasa", "rabu")
hariakhir =("kamis", "jumat", "sabtu")

hari = (hariawal, hariakhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [19]:
pertama = (100)
kedua = (200, 400, 600)
ketiga = (300)
keempat = (400, 800)
nested_tuple = (pertama, kedua, ketiga, keempat)

print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


In [20]:
#latihan 6

dictMahasiswa = {"Nama":"Muhamad Fahmi", "NIM":"2022071026", "Prodi":"Informatika", "Universitas":"UPJ"}

print(dictMahasiswa)
print(dictMahasiswa["Nama"])


{'Nama': 'Muhamad Fahmi', 'NIM': '2022071026', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}
Muhamad Fahmi


In [6]:
#latihan 7
#Inisiasi Set
set_01 = {4,5,6,2}
print("set_01 = ", set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])

print(type(set_02))
print("set_03 = ", set_03)

print("\nmenambah")
set_01.add(576)
print(set_01)

print("\nmenghapus")
set_01.discard(6)
print(set_01)

print("\nunion")
print(set_01|set_03)

print("\nintersection")
print(set_01&set_03)

print("\ndifference")
print(set_01-set_03)

print("\nsymmetric difference")
print(set_01^set_03)

set_01 =  {2, 4, 5, 6}
<class 'set'>
set_03 =  {1, 2, 3, 4}

menambah
{576, 2, 4, 5, 6}

menghapus
{576, 2, 4, 5}

union
{576, 1, 2, 3, 4, 5}

intersection
{2, 4}

difference
{576, 5}

symmetric difference
{576, 1, 3, 5}


In [21]:
#latihan 8
red = {"dandelions", "leaves", "fire hydrant"}
green = {"rose", "blood", "leaves", "fire hydrant"}

print(red|green)
print(red&green)

{'fire hydrant', 'dandelions', 'blood', 'rose', 'leaves'}
{'fire hydrant', 'leaves'}


In [5]:
#latihan 9
import pandas as pd

df = pd.DataFrame([
    [1, "Informatika", 50, 30, 20],
    [2, "Sistem Informasi", 55, 30, 25],
    [3, "Teknik Sipil", 40, 30, 10]
])

df.columns = ["No", "Prodi", "Mahasiswa", "laki-laki", "Perempuan"]
df.style.hide(axis='index')

In [4]:
#latihan 10
import numpy as np

matrix = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
    ])

print(matrix)

print("\nTranspose:")
print(matrix.T)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
